name: build

on:
  push:
    branches:
      - main

env:
  ARTIFACT_NAME: main.pdf
  DOCKER_IMAGE_NAME: nd02110114/latex-env-template
  # Google Driveへアップロードをするかどうか
  DRIVE_UPLOAD: false
  # Google Driveのアップロード先のディレクトリ
  DRIVE_BASE_DIR: /XXX/XXXX

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: ${{ env.DOCKER_IMAGE_NAME }}:latest
      options: --user root -v ${{ github.workspace }}:/workdir
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Create PDF
        run: latexmk -l main.tex
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: pdf
          path: ./${{ env.ARTIFACT_NAME }}
      - name: Upload to Google Drive
        if: ${{ env.DRIVE_UPLOAD }} == true
        uses: wei/rclone@v1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        with:
          args: sync ${{ env.ARTIFACT_NAME }} googledrive:${{ env.DRIVE_BASE_DIR }}
