name: Lint

on:
  pull_request:
    # Pull Request かつ以下のファイルに変更があった場合、このWorkflowを実行
    paths:
      - "prh.yml"
      - ".textlintrc"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/lint.yaml"
      - "**.tex"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Setup node environment
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Restore cache if available
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Run lint
        run: npm ci && npm run lint
      - name: Run reviewdog
        if: failure()
        uses: tsuyoshicho/action-textlint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          textlint_flags: "*/*.tex"
